# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_year',
            old_name='sem',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(choices=[(1, b'1st'), (2, b'2nd'), (3, b'3rd'), (4, b'4th')]),
        ),
    ]
