# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160826_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school_year',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='school_year',
            name='semester',
            field=models.IntegerField(choices=[(1, b'1st'), (2, b'2nd'), (3, b'Summer')]),
        ),
    ]
