# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160826_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
